@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US02

autonumber

actor "Human Resources\nManager" as HRM
participant ":System" as System

activate HRM

    HRM -> System : asks to register a new job
    activate System

        System --> HRM : requests job details (name, description)
    deactivate System

    HRM -> System : provides requested job details
    activate System

        System --> HRM : displays an error dialogue
    deactivate System

@enduml