@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "StationTypeMapper" as LOC_MAPPER
participant "listStationTypes : List<StationType>" as LOC_LIST
participant "listStationTypesDTO : List<StationType>" as LOC_DTO
participant "objDTO : StationTypeDTO" as OBJ_DTO

autonumber 27
-> LOC_MAPPER
autonumber 27.1
    activate LOC_MAPPER
    LOC_MAPPER --> LOC_DTO** : create()
    loop for each object in listStationTypes
        LOC_MAPPER -> LOC_LIST : obj = get(i)
            activate LOC_LIST
            deactivate LOC_LIST
        LOC_MAPPER -> LOC_MAPPER : objDTO = toDTO(obj)
        activate LOC_MAPPER
        LOC_MAPPER --> OBJ_DTO** : create()
        deactivate LOC_MAPPER
        LOC_MAPPER -> LOC_LIST : add(objDTO)
            activate LOC_LIST
            deactivate LOC_LIST
    end loop
<- LOC_MAPPER : listStationTypesDTO
deactivate LOC_MAPPER
@enduml