@startuml
' Definição das classes com atributos
class Address {
  address_id
  Street
  "Floor or Apt"
  ZipCode
  Town
  City
  Country
}

class Customer {
  customer_id
  customer_name
  phone_number
  email
  IBAN
  NIF
  customer_type
  address_id
  customer_legacy_id
}

class "Order" {
  order_id
  Customercustomer_id
  order_date
  delivery_date
  order_status
  delivery_address_id
}

class "Ordered Items" {
  Orderorder_id
  Variantsvariant_id
  quantity
}

class "Production Order" {
  production_order_id
  Orderorder_id
  Variantsvariant_id
  priority
  OrderVariantsvariant_id
}

class Variants {
  variant_id
  product_id
  variant_name
}

class "Bill of materials" {
  parent_variant_id
  quantity
  child_variant_id
}

class "Bill of Operations" {
  operation_id
  operation_number
  family_id
}

class Category {
  category_id
  category_name
}

class Product {
  product_id
  product_name
  Categorycategory_id
  product_description
  product_legacy_id
  family_id
}

class "Product Family" {
  family_id
  family_name
  family_legacy_id
}

class "Product Options" {
  option_id
  option_name
  Productproduct_id
}

class "Options Values" {
  value_id
  value_name
  option_id
}

class STOCK {
  variant_id
  quantity_available
}

class Workstation {
  workstation_id
  workstation_name
  workstation_description
  workstation_type_id
  workstation_legacy_id
  Facilityfacility_id
  workstation_kind
}

class "Workstation Type" {
  workstation_type_id
  workstation_type_name
  workstation_type_legacy_id
}

class Operation {
  operation_id
  legacy_operation_id
  operation_description
  time_required
}


Customer "1"---"1" Address
"Order" "1*"---"1" Customer
"Order" "1"---"0*" Address
"Ordered Items" "1*"--- "1" "Order"
"Ordered Items" "1*"---"1" Variants
"Production Order" "1*"--- "0*""Order"
"Production Order" "1"---"1" Variants
"Bill of materials" "1"---- "0*" Variants
"Bill of materials" "1"---"1" Variants
Variants "1*"---"1" Product
Product "1*"---"0*" Category
Product "1*"---"0*" "Product Family"
"Product Options" "1*"---"1"  Product
"Options Values" "1*" --- "1" "Product Options"
STOCK "1"----"1" Variants
Workstation "1*"---"o*" Facility
Workstation "1"---"1" "Workstation Type"
Operation "1"---"1" "Bill of Operations"
Operation "1"--- "1" "Workstation Type"
"Bill of Operations" "1" --- "1" "Product Family"
Address "0*" --- "1" Facility
Variants "1"--- "1" "Options Values"
@enduml
