@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
title Domain Model US27

skinparam classAttributeIconSize 0

hide circle
hide methods

class GreenSpaceManager {
}

class GreenSpace {
    greenSpaceName
    greenSpaceStreet
    greenSpaceManagerEmail
    greenSpaceArea
}

class GreenSpaceType{
     GARDEN
     MEDIUM_SIZED_PARK
     LARGE_SIZED_PARK
}

GreenSpaceManager "1" -- "0..*" GreenSpace : manages >
GreenSpace "1" -- "1" GreenSpaceType : has >

@enduml