@startuml
skinparam packageStyle rectangle
skinparam classAttributeIconSize 0

title US07 - View station details \n(buildings + cargo demand/supply from nearby industries)

autonumber

actor "Player" as PLAYER
participant ":ViewStationDetailsUI" as UI
participant ":ViewStationDetailsController" as CTRL
participant "Repositories" as REPOS_SINGLETON
participant "repositories\n:Repositories" as REPOS
participant "StationRepository" as STAREPOS
participant ":StationMapper" as STATIONMAPPER
participant "objDto\n:StationDto" as STATIONDTO
participant "StationDtoList\n:List<StationDto>" as STATIONDTOLIST
participant "Station" as STATION
participant "BuildingMapper" as BUILDINGMAPPER
participant "buildingDto\n:BuildingDto" as BUILDINGDTO
participant "buildingDtoList\n:List<BuildingDto>" as BUILDINGDTOLIST

participant "ApplicationSession" as APP_SESSION
participant "appSession\n:ApplicationSession" as APP_SESSION_SINGLETON
participant "currentSession\n:UserSession" as CURRENT_SESSION

participant "mapRepository\n:MapRepository" as MAP_REPO
participant "Map" as MAP
participant ":IndustryMapper" as INDUSTRYMAPPER
participant "industryDto\nIndustryDto" as INDUSTRYDTO
participant "industryDtoList\n:List<IndustryDto>" as INDUSTRYDTOLIST
participant "stationDetailsDto\n:StationDetailsDto" as STATIONDETAILSDTO
participant "Industry" as INDUSTRY

activate PLAYER

  PLAYER -> UI : requests list of stations
  
  activate UI

    UI --> CTRL** : create
    
    UI -> CTRL : getAvailableStations()
    
    activate CTRL

      CTRL -> REPOS_SINGLETON : getInstance()
  
      activate REPOS_SINGLETON
      
        REPOS_SINGLETON --> CTRL : repositories
      
      deactivate REPOS_SINGLETON

      CTRL -> REPOS : getStationRepository()

      activate REPOS

        REPOS --> CTRL : stationRepository

      deactivate REPOS

      CTRL -> STAREPOS : getAllStations()

      activate STAREPOS

        STAREPOS -> STATIONMAPPER : toDtoList(stations)

        activate STATIONMAPPER

          group Transform the List to DTO

            loop for each Station in the list stations

              STATIONMAPPER -> STATIONMAPPER : toDto(station)

              activate STATIONMAPPER

                STATIONMAPPER --> STATIONDTO** : create

              deactivate STATIONMAPPER

              STATIONMAPPER -> STATIONDTOLIST : add(objDto)

            end

          end

          STATIONMAPPER --> STAREPOS : List<StationDto>
        
        deactivate STATIONMAPPER

        STAREPOS --> CTRL : List<StationDto>

      deactivate STAREPOS

      CTRL --> UI : list of stations
    
    deactivate CTRL

    UI --> PLAYER : shows list of stations
  
  deactivate UI

  PLAYER -> UI : selects a station

  activate UI

    UI -> CTRL : getStationDetails(stationDto)
  
    activate CTRL

      CTRL -> STAREPOS : getStationDetails(stationId)

      activate STAREPOS

        STAREPOS --> CTRL : station
      
      deactivate STAREPOS

      CTRL -> STATION : getBuildings()
      
      activate STATION

        STATION -> BUILDINGMAPPER : toDtoList(buildings)

        activate BUILDINGMAPPER

          group Transform the List to DTO

            loop for each Building in the list buildings

              BUILDINGMAPPER -> BUILDINGMAPPER : toDto(building)

              activate BUILDINGMAPPER

                BUILDINGMAPPER --> BUILDINGDTO** : create

              deactivate BUILDINGMAPPER

              BUILDINGMAPPER -> BUILDINGDTOLIST : add(buildingDto)

            end

          end

          BUILDINGMAPPER --> STATION : List<BuildingDto>
        
        deactivate BUILDINGMAPPER
      
        STATION --> CTRL : List<BuildingDto>
      
      deactivate STATION

      ref over CTRL
        partial-SD_getCurrentMap
      end ref

      CTRL -> MAP : getNearbyIndustries(station)
      
      activate MAP
      
        MAP --> CTRL : List<Industry>
      
      deactivate MAP

      loop for each Industry in the list

        CTRL -> INDUSTRY : getResources()

        activate INDUSTRY

        note right of CTRL
          Add produced and demanded resource\n
          to cargo list (for later UI display)
        end note

          INDUSTRY --> CTRL: List<ResourceDto>

        deactivate INDUSTRY
      
      end

      CTRL --> STATIONDETAILSDTO** : create(buildingsDto, industries, resourcesDto)
      
      CTRL --> UI : stationDetailsDto
      
    deactivate CTRL

    UI --> PLAYER : shows station details

  deactivate UI

deactivate PLAYER

@enduml