@startuml
skinparam linetype ortho
skinparam package {
  BackgroundColor #F9E79F
  BorderColor Black
}

actor "Show Designer" as SD
participant "DecommissionFigureUI" as UI
participant "Decommission FigureController" as Controller
participant "FigureService" as Service
participant "FigureRepository" as Repo
participant "FigureStatus" as FigSt

    SD -> UI : asks to decommission a figure
    UI -> SD : asks to enter the code and version
    SD -> UI : insert the figure information
    UI -> Controller :  decommissionFigure(code, version)
    Controller -> Service : decommissionFigure(code, version)
    Service -> Repo : findByCodeAndVersion(code, version)
    alt Figure not found
        Repo -> Service : throw IllegalArgumentException
        Service --> Controller : Sent error message
        Controller --> UI : Show error message
        UI -> SD : Display error
    else Figure found
        Repo -> Service : figure found
        Service -> Figure : decommission()
        Figure -> FigSt : new status
        Service -> Repo : save(figure)
        Service --> Controller : Sent success message
        Controller --> UI : Show success message
        UI -> SD : Display a message
    end


@enduml
