@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "ResourceTypeMapper" as RESOURCE_MAPPER
participant "listResourceTypes : List<ResourceType>" as RESOURCE_LIST
participant "listResourceTypesDTO : List<ResourceTypeDTO>" as RESOURCE_DTO
participant "objDTO : ResourceTypeDTO" as OBJ_DTO

autonumber 39
-> RESOURCE_MAPPER
autonumber 39.1
    activate RESOURCE_MAPPER
    RESOURCE_MAPPER --> RESOURCE_DTO** : create()
    loop for each object in listResourceTypes
        RESOURCE_MAPPER -> RESOURCE_LIST : obj = get(i)
            activate RESOURCE_LIST
            deactivate RESOURCE_LIST
        RESOURCE_MAPPER -> RESOURCE_MAPPER : objDTO = toDTO(obj)
        activate RESOURCE_MAPPER
        RESOURCE_MAPPER --> OBJ_DTO** : create()
        deactivate RESOURCE_MAPPER
        RESOURCE_MAPPER -> RESOURCE_LIST : add(objDTO)
            activate RESOURCE_LIST
            deactivate RESOURCE_LIST
    end loop
<- RESOURCE_MAPPER : listResourceTypesDTO
deactivate RESOURCE_MAPPER
@enduml