should those DTOs be mentioned in this class diagram or not?

@startuml
class AgendaController {
    -agenda: Agenda
    -repositories: Repositories
    +addAgendaEntry(task: Task, entryDate: String): boolean
    +getActiveAgendaEntries(): ArrayList<AgendaEntry>
    +getUnassignedVehicles(ae: AgendaEntry): ArrayList<Vehicle>
    -addMinutesToSchedule(schedule: ArrayList<DaySchedule>, date: LocalDate, minutes: int): void
    -getUsedMinutesForDate(schedule: ArrayList<DaySchedule>, date: LocalDate): int
    -calculateTaskEndDate(startDate: LocalDate, durationInMinutes: int): LocalDate
}

class Agenda {
    -agendaEntries: ArrayList<AgendaEntry>
}

class AgendaEntry {
    -associatedTask: Task
    -team: Team
    -date: LocalDate
    -vehicles: ArrayList<Vehicle>
}

class Team {
    -skills: ArrayList<Skill>
    -collaborators: ArrayList<Collaborator>
}

class Collaborator {
    -name: String
    -birthDate: LocalDate
    -admissionDate: LocalDate
    -address: String
    -mobileNumber: String
    -email: String
    -taxPayerNumber: String
    -identificationDocumentType: String
    -documentIdentificationNumber: String
    -skills: ArrayList<Skill>
    -job: Job
}


class Repositories {
    -instance: Repositories
    -collaboratorsRepository: CollaboratorsRepository
    -skillsRepository: SkillsRepository
    -jobsRepository: JobsRepository
    -authenticationRepository: AuthenticationRepository
}

class Skill {
    -nameOfTheSkill: String
}

AgendaController "1" -- "1" Agenda
AgendaController "1" -- "1" Repositories
Agenda "1" -- "*" AgendaEntry
AgendaEntry "1" -- "1" Team
Team "1" -- "*" Collaborator
Team "1" -- "*" Skill
Collaborator "*" -- "*" Skill
@enduml