@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

'title Domain Model

class User{
    name
    email
    password
}

class Role{
    name
    description
}

class  Map{
    name
    width
    height
}

class Scenario{
    name
    description
    historicalRestrictions
}

class City{
    name
    nBlocks
}

class House{
    id
}

class Industry{
    name
}

class IndustryType{
    name
    description
}

class Station{
    name
    upgrades
}

class StationType{
    name
    description
}

class RailwayLine{
    length
    type
}

class Train {
    id
}

class Locomotive{
    id
    power
    acceleration
    topSpeed
    startYearOfOperation
    acquisitionPrice
}

class LocomotiveType{
    name
    description
}

class TimeRestrictions{
    startTime
    endTime
}

class Carriage{
    id
    capacity
}

class CarriageType{
    name
}

class Route{
    id
}

class Cargo{
    quantity
}

class Location {
    coordinateX
    coordinateY
}

User "*" --> "1" Role : has
User "1" --> "*" Map : manages

Map "1" --> "*" Scenario : uses
Map "1" --> "*" City : contains
Map "*" --> "*" Train : has
Map "1" --> "*" Industry : contains
Map "1" --> "*" Station : contains

City "1" --> "*" House : contains
City "1" --> "1" Location : located at

Train "1" --> "1" Locomotive : has
Train "1" --> "*" Carriage : has

Locomotive "*" -- "1" LocomotiveType : has
LocomotiveType "*" --> "*" Scenario : Locomotive restrictions

RailwayLine "1" --> "2" Station : connects

Route "*" --> "*" Station : has

Carriage "*" --> "1" Cargo : carries
Carriage "1" --> "1" CarriageType : has

Industry "1" --> "1" IndustryType : has
Industry "*" --> "1" Cargo : produces
Industry "1" --> "0..*" Cargo: receives
Industry "1" --> "1" Location : located at

IndustryType "*" --> "*" Scenario : Industry restrictions

Station "1" --> "1" StationType : has
Station "1" --> "1" Location : located at

TimeRestrictions "1" <-- "*" Scenario : has

House "1" --> "1" Location : located at

@enduml
