@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

'title Domain Model

class User{
    name
    email
    password
}

class Role{
    name
    description
}

class  Map{
    name
    width
    height
}

class Scenario{
    name
    description
    historicalRestrictions
}

class City{
    name
    location
    nBlocks
}

class House{}

class Industry{
    name
    location
}

class IndustryType{
    name
    description
}

class Station{
    name
    location
    upgrades
}

class StationType{
    name
    description
}

class RailwayLine{
    id
    length
    type
}

class Train {
    id
}

class Locomotive{
    id
    power
    acceleration
    topSpeed
    startYearOfOperation
    aquisitionPrice
}

class LocomotiveType{
    name
    description
}

class timeRestrictions{
    startTime
    endTime
}

class Carriage{
    id
    type
    capacity
}

class Route{
    id
}

class Cargo{
    type
    quantity
}

User "*" -- "1" Role : has
User "1" -- "*" Map : manages

Map "1" -- "*" Scenario : uses
Map "1" -- "*" City : contains
Map "*" -- "*" Train : has
Map "1" -- "*" Industry : contains
Map "1" -- "*" Station : contains

City "1" -- "*" House : contains

Train "1" -- "1" Locomotive : has
Train "1" -- "*" Carriage : has

Locomotive "*" -- "1" LocomotiveType : has
LocomotiveType "*" -- "*" Scenario : Locmotive restrictions

RailwayLine "1" -- "2" Station : connects

Route "*" -- "*" Station : has

Carriage "*" -- "1" Cargo : carries

Industry "1" -- "1" IndustryType : has
IndustryType "*" -- "*" Scenario : Industry restrictions

Station "1" -- "1" StationType : has

timeRestrictions "1" -- "*" Scenario : Time restrictions

@enduml