@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as HRM
participant ":AssignSkillUI" as UI
participant ":AssignSkillController" as AssSkCTRL
participant "repositories\n:Repositories" as REP
participant "collaboratorsRepository:\nCollaboratorsRepository" as CollaboratorsRepository
participant "skillsRepository:\nSkillsRepository" as SkillsREP

activate HRM

    HRM -> UI : asks to assign a skill to a collaborator

    activate UI

        UI -> AssSkCTRL** : create
        UI -> AssSkCTRL : getCollaboratorList()

        activate AssSkCTRL
            AssSkCTRL -> REP: getInstance()

            activate REP
                REP --> AssSkCTRL: repositories
            deactivate REP

            AssSkCTRL -> REP: getCollaboratorsRepository()

            activate REP
                REP --> AssSkCTRL: collaborators repository
            deactivate REP

            AssSkCTRL -> CollaboratorsRepository: getCollaboratorList()

            activate CollaboratorsRepository
                CollaboratorsRepository --> AssSkCTRL: collaborators list
            deactivate CollaboratorsRepository

            AssSkCTRL --> UI: collaborators list

        deactivate AssSkCTRL

        UI --> HRM : shows collaborators list and asks to select one

    deactivate UI

    HRM -> UI : selects a collaborator

    activate UI

        UI -> AssSkCTRL: getSkillsList()

        activate AssSkCTRL
            AssSkCTRL -> REP: getInstance()

            activate REP
                REP --> AssSkCTRL: respositories
            deactivate REP

            AssSkCTRL -> SkillsREP: getSkillsRepository()

            activate SkillsREP
                SkillsREP --> AssSkCTRL: skillsRepository
            deactivate SkillsREP

            AssSkCTRL -> SkillsREP: getSkillsList()

            activate SkillsREP
                SkillsREP --> AssSkCTRL: skills list
            deactivate SkillsREP

            AssSkCTRL --> UI: skills list

        deactivate AssSkCTRL

        UI --> HRM : shows skills list and asks to select one

    deactivate UI

    HRM -> UI: selects a skill

    activate UI

        UI -> AssSkCTRL: assignSkill(collaborator, skill)

        activate AssSkCTRL
            AssSkCTRL -> CollaboratorsRepository: assignSkill(collaborator, skill)
            activate CollaboratorsRepository
                CollaboratorsRepository --> AssSkCTRL: success
            deactivate CollaboratorsRepository

            AssSkCTRL --> UI: success

        deactivate AssSkCTRL

        UI --> HRM: displays operation success

    deactivate UI

deactivate HRM
@enduml